### ISSUE TITLE
Image Size and format Issue

### ISSUE THREAD

**Issue by XaibiAslam** [psyon/php-qrcode#4]
Hi,
I'm using your code, and it's great! However, when I increase the size of my QR code, it gets a bit blurry. Also, it's not working with the SVG format. How can we fix these issues?

**Comment by psyon** [comment]
If the image is blurry when you are displaying it on a page, it may be due to the browser scaling it to match the display size of the image in HTML.  For SVG support, you will need to use the upstream project.  I stripped out everything I didn't need, and created this repo just to simplify the code I was using. 

https://github.com/kreativekorp/barcode

**Comment by XaibiAslam** [comment]
Thankyou for clarifying me.
